// One-shot refactor: pull the 20 embedded base64 images out of src/App.jsx
// into real PNG files + a generated src/images.js that imports them, so Vite
// emits them as separate, lazily-fetched assets instead of inlining ~700KB
// of base64 into the JS bundle. Question data and all logic are untouched.
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const APP = path.join(ROOT, "src", "App.jsx");
const lines = fs.readFileSync(APP, "utf8").split("\n");

// Locate the data lines by content (don't trust fixed indices).
const iData = lines.findIndex((l) => l.startsWith("const DATA = "));
const iStrips = lines.findIndex((l) => l.trim() === "const STRIPS = DATA.strips;");
const iMascots = lines.findIndex((l) => l.startsWith("const MASCOTS = "));
const iMascotImgs = lines.findIndex((l) => l.trim() === "const MASCOT_IMGS = MASCOTS.imgs;");
if ([iData, iStrips, iMascots, iMascotImgs].some((i) => i < 0)) {
  throw new Error("Could not locate one of the data binding lines");
}

const DATA = JSON.parse(lines[iData].replace(/^const DATA = /, "").replace(/;\s*$/, ""));
const MASCOTS = JSON.parse(lines[iMascots].replace(/^const MASCOTS = /, "").replace(/;\s*$/, ""));

const stripsDir = path.join(ROOT, "src", "img", "strips");
const mascotsDir = path.join(ROOT, "src", "img", "mascots");
fs.mkdirSync(stripsDir, { recursive: true });
fs.mkdirSync(mascotsDir, { recursive: true });

function writeImg(dir, key, dataUri) {
  const b64 = dataUri.replace(/^data:image\/png;base64,/, "");
  fs.writeFileSync(path.join(dir, key + ".png"), Buffer.from(b64, "base64"));
}

const stripKeys = Object.keys(DATA.strips);
const mascotKeys = Object.keys(MASCOTS.imgs);
stripKeys.forEach((k) => writeImg(stripsDir, k, DATA.strips[k]));
mascotKeys.forEach((k) => writeImg(mascotsDir, k, MASCOTS.imgs[k]));

// Generate src/images.js with explicit imports (all keys are JS-safe idents).
const imgJs = [
  "// AUTO-GENERATED by scripts/extract-images.cjs — do not edit by hand.",
  "// Each import becomes a separate hashed asset that the browser fetches",
  "// only when the corresponding <img> renders (natural lazy-loading).",
  ...stripKeys.map((k) => `import strip_${k} from "./img/strips/${k}.png";`),
  ...mascotKeys.map((k) => `import mascot_${k} from "./img/mascots/${k}.png";`),
  "",
  "export const STRIPS = {",
  ...stripKeys.map((k) => `  ${JSON.stringify(k)}: strip_${k},`),
  "};",
  "",
  "export const MASCOT_IMGS = {",
  ...mascotKeys.map((k) => `  ${JSON.stringify(k)}: mascot_${k},`),
  "};",
  "",
].join("\n");
fs.writeFileSync(path.join(ROOT, "src", "images.js"), imgJs);

// Rewrite App.jsx: slim DATA (drop strips) + MASCOTS (drop imgs), import the maps.
lines[0] = lines[0] + '\nimport { STRIPS, MASCOT_IMGS } from "./images.js";';
lines[iData] = "const DATA = " + JSON.stringify({ items: DATA.items }) + ";";
lines[iStrips] = "// STRIPS now imported from ./images.js (externalized PNGs)";
lines[iMascots] = "const MASCOTS = " + JSON.stringify({ pools: MASCOTS.pools }) + ";";
lines[iMascotImgs] = "// MASCOT_IMGS now imported from ./images.js (externalized PNGs)";
fs.writeFileSync(APP, lines.join("\n"));

console.log(`Wrote ${stripKeys.length} strips + ${mascotKeys.length} mascots.`);
console.log("Strip keys:", stripKeys.join(", "));
console.log("Mascot keys:", mascotKeys.join(", "));
