// AUTO-GENERATED by scripts/extract-images.cjs — do not edit by hand.
// Each import becomes a separate hashed asset that the browser fetches
// only when the corresponding <img> renders (natural lazy-loading).
import strip_afib from "./img/strips/afib.png";
import strip_asystole from "./img/strips/asystole.png";
import strip_first_degree from "./img/strips/first_degree.png";
import strip_sinus_brady from "./img/strips/sinus_brady.png";
import strip_sinus_tach from "./img/strips/sinus_tach.png";
import strip_svt from "./img/strips/svt.png";
import strip_third_degree from "./img/strips/third_degree.png";
import strip_torsades from "./img/strips/torsades.png";
import strip_vfib from "./img/strips/vfib.png";
import strip_vtach from "./img/strips/vtach.png";
import mascot_correct_thumbs from "./img/mascots/correct_thumbs.png";
import mascot_correct_fist from "./img/mascots/correct_fist.png";
import mascot_incorrect_think from "./img/mascots/incorrect_think.png";
import mascot_question_point from "./img/mascots/question_point.png";
import mascot_rationale_open from "./img/mascots/rationale_open.png";
import mascot_rationale_heart from "./img/mascots/rationale_heart.png";
import mascot_rationale_clip from "./img/mascots/rationale_clip.png";
import mascot_home_present from "./img/mascots/home_present.png";
import mascot_home_wave from "./img/mascots/home_wave.png";
import mascot_home_arms from "./img/mascots/home_arms.png";

export const STRIPS = {
  "afib": strip_afib,
  "asystole": strip_asystole,
  "first_degree": strip_first_degree,
  "sinus_brady": strip_sinus_brady,
  "sinus_tach": strip_sinus_tach,
  "svt": strip_svt,
  "third_degree": strip_third_degree,
  "torsades": strip_torsades,
  "vfib": strip_vfib,
  "vtach": strip_vtach,
};

export const MASCOT_IMGS = {
  "correct_thumbs": mascot_correct_thumbs,
  "correct_fist": mascot_correct_fist,
  "incorrect_think": mascot_incorrect_think,
  "question_point": mascot_question_point,
  "rationale_open": mascot_rationale_open,
  "rationale_heart": mascot_rationale_heart,
  "rationale_clip": mascot_rationale_clip,
  "home_present": mascot_home_present,
  "home_wave": mascot_home_wave,
  "home_arms": mascot_home_arms,
};
